version: '3.8'

networks:
  ck-io:

volumes:
  jenkins-docker-certs:

services:
  jenkins:
    build:
      context: ./config/jenkins
      dockerfile: ./Dockerfile
    container_name: jenkins-blueocean1.1
    restart: always
    ports:
      - '1001:8080'
      - '1002:50000'
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes:
      - jenkins-docker-certs:/certs/client:ro
      - './volumes/jenkins/jenkins-data:/var/jenkins_home'
      - './volumes/jenkins/home:/home'
    depends_on:
      - jenkins-docker
    networks:
      - ck-io

  jenkins-docker:
    image: docker:dind
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - jenkins-docker-certs:/certs/client
      - './volumes/jenkins/jenkins-data:/var/jenkins_home'
    restart: always
    command: --storage-driver=overlay2
    networks:
      ck-io:
        aliases:
          - docker
