---
- name: Production | Server installation
  hosts: infra
  remote_user: root
  tasks:
    - include_vars:
        file: vars.yml
    - include_role:
        name: init
    - include_role:
        name: geerlingguy.docker
    - include_role:
        name: geerlingguy.nginx

